services:
  mysql:
    image: mysql:8.4
    container_name: surveylab_mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: surveylab
      MYSQL_USER: surveylab_user
      MYSQL_PASSWORD: surveylab_password
      MYSQL_ROOT_PASSWORD: root_password

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - surveylab_network

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-proot_password"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  mysql_data:

networks:
  surveylab_network:
    driver: bridge